export enum ProjectSyncActionTypes {
  SET_SELECTED_PROJECT_ID = "SET_SELECTED_PROJECT_ID",

}

export enum ProjectActionTypes {
  FETCH_PROJECTS = "FETCH_PROJECTS",
  FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS",
  FETCH_PROJECTS_ERROR = "FETCH_PROJECTS_ERROR"
}

