export enum ProjectSyncActionTypes {
  SET_SELECTED_PROJECT_ID = "SET_SELECTED_PROJECT_ID",
}

export enum ProjectActionTypes {
  FETCH_PROJECTS = "FETCH_PROJECTS",
  FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS",
  FETCH_PROJECTS_ERROR = "FETCH_PROJECTS_ERROR",
  TRIGGER_CREATE_NEW_PROJECT = "TRIGGER_CREATE_NEW_PROJECT",
  TRIGGER_PATCH_PROJECT = "TRIGGER_PATCH_PROJECT",
  CREATE_NEW_PROJECT = "CREATE_NEW_PROJECT",
  PATCH_PROJECT = "PATCH_PROJECT",
  DELETE_PROJECT = "DELETE_PROJECT",
}


